# Generated by Django 5.2.7 on 2025-10-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL ảnh đại diện cho danh mục (tùy chọn)'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_options',
            field=models.CharField(blank=True, help_text='Danh sách màu sắc (ngăn cách bởi dấu phẩy, ví dụ: Đỏ, Xanh, Đen)', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='Các thông số kỹ thuật (mỗi dòng một mục, hoặc dán dạng văn bản)'),
        ),
    ]
