# Generated by Django 5.2.7 on 2025-11-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_image_url_product_color_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tiêu đề banner', max_length=200)),
                ('image_url', models.URLField(help_text='URL ảnh banner')),
                ('link', models.URLField(blank=True, help_text='Link khi click vào banner (tùy chọn)')),
                ('is_featured', models.BooleanField(default=False, help_text='Banner nổi bật (hiển thị trên carousel)')),
                ('discount_info', models.CharField(blank=True, help_text='Thông tin giảm giá (ví dụ: Giảm 50%)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
