# Generated by Django 5.2.7 on 2025-11-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash_sale_end',
            field=models.DateTimeField(blank=True, help_text='Thời gian kết thúc Flash Sale', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Giá Flash Sale (để trống nếu không tham gia)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_sale_start',
            field=models.DateTimeField(blank=True, help_text='Thời gian bắt đầu Flash Sale', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_sale_stock',
            field=models.PositiveIntegerField(default=0, help_text='Số lượng dành cho Flash Sale (0 = không giới hạn riêng)'),
        ),
    ]
